# Generated by Django 3.2.4 on 2021-07-05 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('idMetodo', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Metodo')),
                ('Pago', models.CharField(max_length=10, verbose_name='Metodo de Pago')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('numId', models.IntegerField(max_length=10, primary_key=True, serialize=False, verbose_name='Número de Identificación')),
                ('Nombre', models.CharField(max_length=50, verbose_name='Nombre Completo')),
                ('telefono', models.IntegerField(max_length=20, verbose_name='Número de Teléfono')),
                ('Direccion', models.CharField(max_length=20, verbose_name='Dirección')),
                ('Email', models.CharField(max_length=50, verbose_name='Email')),
                ('Pais', models.CharField(max_length=10, verbose_name='Pais')),
                ('Contrasenna', models.CharField(max_length=10, verbose_name='Contraseña')),
                ('MetodoPago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GreenPanda.metodopago')),
            ],
        ),
    ]
