# Generated by Django 3.2.4 on 2021-07-05 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPanda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='Imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
