# Generated by Django 3.2.4 on 2021-07-05 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPanda', '0002_proveedor_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='numId',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Número de Identificación'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.IntegerField(verbose_name='Número de Teléfono'),
        ),
    ]
