# Generated by Django 3.2.4 on 2021-07-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenPanda', '0003_auto_20210705_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='Direccion',
            field=models.CharField(max_length=50, verbose_name='Dirección'),
        ),
    ]
